In [6]:
import pandas as pd # not sure I'll use it but just in case
import numpy as np

In [31]:
with open('../input/04-input.txt', 'r') as f:
    drawings = [int(x) for x in f.readline().rstrip().split(',')]
    f.readline() #removing blank
    boards = []
    tempboard = []
    for line in f:
        if line == "\n":
            boards.append(np.array(tempboard))
            tempboard = []
        else:
            tempboard.append([int(x) for x in line.split()])
print(boards[0])
drawings[0:8]

[[25 29 78 57 69]
 [47 51  7 21 82]
 [61 81 99 53 30]
 [50 80 41 94 46]
 [ 9 37 48 71 91]]


[63, 23, 2, 65, 55, 94, 38, 20]

In [88]:
def find_board_win(test_board, drawings):
    marked = np.zeros(shape=(5,5))
    i = 0
    while 5 not in np.append(marked.sum(axis=0), marked.sum(axis=1)):
        mark_here = np.where(test_board == drawings[i])
        if test_board[mark_here].size != 0:
            marked[mark_here] = 1
        i += 1
    remain_sum = test_board[np.where(marked == 0)].sum()
    score = remain_sum * drawings[i-1]
    return i-1, score

In [89]:
# testing block
test_board = np.array([[14, 21, 17, 24, 4],[10, 16, 15, 9, 19],[18, 8, 23, 26, 20],[22, 11, 13, 6, 5,],[2, 0, 12, 3, 7]])
print('board', test_board)
test_drawing = [int(x) for x in "7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1".split(',')]
print('drawing', test_drawing[0:12])
find_board_win(test_board, test_drawing)

board [[14 21 17 24  4]
 [10 16 15  9 19]
 [18  8 23 26 20]
 [22 11 13  6  5]
 [ 2  0 12  3  7]]
drawing [7, 4, 9, 5, 11, 17, 23, 2, 0, 14, 21, 24]


(11, 4512)

In [90]:
wins = [find_board_win(board, drawings) for board in boards]
wins[0:5]

[(49, 40470), (61, 19380), (53, 29696), (51, 14469), (54, 22724)]

In [93]:
min_index = 100000
for board in boards:
    win_index, win_score = find_board_win(board, drawings)
    if win_index < min_index:
        min_index = win_index
        min_score = win_score
    

63424

In [94]:
# answer
min_score  

63424

In [96]:
# Part 2
max_index = 0
for board in boards:
    win_index, win_score = find_board_win(board, drawings)
    if win_index > max_index:
        max_index = win_index
        max_score = win_score
# answer
max_score

23541